// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Curry      from "bs-platform/lib/es6/curry.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

var Image = /* module */[];

var Element = /* module */[];

var Document = /* module */[];

var ImageData = /* module */[];

var CanvasContext = /* module */[];

var Canvas = /* module */[];

function onLoad(callback) {
  return (function () {
      var img = this ;
      var canevas = document.createElement("canevas");
      var context = canevas.getContext("2d");
      canevas.setAttribute("width", Pervasives.string_of_float(img.width));
      canevas.setAttribute("height", Pervasives.string_of_float(img.height));
      context.drawImage(img, 0.0, 0.0);
      return Curry._1(callback, context.getImageData(0.0, 0.0, 0.0, 0.0));
    });
}

function imageDataOfUrl(url) {
  var img = new Image();
  return new Promise((function (resolve, _) {
                img.onload = onLoad((function (result) {
                        return resolve(result);
                      }));
                img.source = url;
                return /* () */0;
              }));
}

export {
  Image          ,
  Element        ,
  Document       ,
  ImageData      ,
  CanvasContext  ,
  Canvas         ,
  onLoad         ,
  imageDataOfUrl ,
  
}
/* No side effect */
